# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polymer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=100)),
                ('mold_temperature', models.FloatField()),
                ('melt_temperature', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='producer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_name', to='materials.Product'),
        ),
        migrations.AddField(
            model_name='polymer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polymer_name', to='materials.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='producer',
            unique_together=set([('product', 'producer_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='polymer',
            unique_together=set([('product', 'polymer_name')]),
        ),
    ]
