# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='polymer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymer', to='materials.Polymer'),
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='materials.Producer'),
        ),
        migrations.AlterUniqueTogether(
            name='polymer',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='producer',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='polymer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='product',
        ),
    ]
